### ISSUE TITLE
Source releases are missing version information

### ISSUE THREAD

**Issue by fkr** [gridscale/gscloud#131]
The source releases are missing the version infos that are compiled into the binaries.
Explanation in this PR: https://github.com/gridscale/gscloud/pull/128

Conclusion: needs to be done with goreleaser.

**Comment by bkircher** [comment]
Perfect, was just about to do this :smiley: 

> Conclusion: needs to be done with goreleaser.


Or somehow massaged into GH Actions. For ideas also see PR #128 .

**Comment by ls42** [comment]
#128 is closed a while now, is there a strategy on how to go forward with this?

**Comment by bkircher** [comment]
Yes. With commits 31f64b8849e32887fd2fa3b5185aa27af01a7b6b and 714dfbee959e0745dd4517cac5023852d735f68d and recently released Git v2.32.0 ([annoncement](https://lore.kernel.org/lkml/xmqqa6o3xj2e.fsf@gitster.g/T/#u)) we create a file RELEASE.txt that contain GIT_COMMIT and VERSION variables. This should habppen automatically when GitHub build the release archive (I hope, not sure what Git version or implementation they use internally).

Things left doing:
- Make Makefile target check if RELEASE.txt file exists and if so, use variables therein (if present) for linker flags. Otherwise use git tools (like now) to determine those values.
- finally, make a release and check if things work like expected :100:

**Comment by bkircher** [comment]
Seemsl like `%(describe)` is not yet working on GitHub: https://github.community/t/support-for-describe-in-export-subst/196618
